### ISSUE TITLE
Previous order/Reorder page

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#86]
![image](https://user-images.githubusercontent.com/8385702/44720999-2da83b00-aae6-11e8-9f3c-a57e05335d30.png)

**Comment by softventure** [comment]
@sawantsh Please take a look. This issue is in web.

**Comment by BhavanaSJain** [comment]
Pending in mobile.

**Comment by sawantsh** [comment]
The header background color is already updated on web, in mobile the order summary is displayed as page as instead of dialogue. attaching screenshot, let me know if the title bar background color is to be changed.

![image](https://user-images.githubusercontent.com/18049665/44982231-cf220780-af92-11e8-9e98-0eff5b7f8efd.png)
